// ============================================
// Zule AI — Balanced-Brace JSON Extractor Tests
// ============================================
//
// Includes example/edge-case unit tests plus the property-based round-trip
// test (Property 28) referenced by tasks.md task 2.7.

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { extractJsonObject } from './jsonExtract';

describe('extractJsonObject (unit)', () => {
  it('returns null for empty input', () => {
    expect(extractJsonObject('')).toBeNull();
  });

  it('returns null when no object is present', () => {
    expect(extractJsonObject('no json here, just prose')).toBeNull();
  });

  it('extracts a plain object', () => {
    expect(extractJsonObject('{"a":1}')).toEqual({ a: 1 });
  });

  it('strips a surrounding ```json code fence', () => {
    const raw = '```json\n{"a":1,"b":[1,2,3]}\n```';
    expect(extractJsonObject(raw)).toEqual({ a: 1, b: [1, 2, 3] });
  });

  it('strips a plain ``` code fence', () => {
    const raw = '```\n{"hello":"world"}\n```';
    expect(extractJsonObject(raw)).toEqual({ hello: 'world' });
  });

  it('tolerates leading commentary before the object', () => {
    const raw = 'Here is the result you asked for:\n\n{"k":42}';
    expect(extractJsonObject(raw)).toEqual({ k: 42 });
  });

  it('tolerates trailing commentary after the object', () => {
    const raw = '{"k":42}\n\nHope that helps!';
    expect(extractJsonObject(raw)).toEqual({ k: 42 });
  });

  it('handles nested objects', () => {
    const obj = { outer: { inner: { deepest: [1, 2, { x: true }] } }, n: 3 };
    expect(extractJsonObject(JSON.stringify(obj))).toEqual(obj);
  });

  it('ignores braces inside string values', () => {
    const raw = '{"text":"this { is not } a brace","n":1}';
    expect(extractJsonObject(raw)).toEqual({ text: 'this { is not } a brace', n: 1 });
  });

  it('honors escape sequences inside strings', () => {
    const raw = '{"text":"escaped \\"quote\\" and \\\\ backslash and a } brace"}';
    expect(extractJsonObject(raw)).toEqual({
      text: 'escaped "quote" and \\ backslash and a } brace',
    });
  });

  it('returns null when input is a JSON array, not an object', () => {
    expect(extractJsonObject('[1,2,3]')).toBeNull();
  });

  it('returns null when the object is unbalanced', () => {
    expect(extractJsonObject('{"a":1')).toBeNull();
  });

  it('skips a stray { in prose and finds the real object later', () => {
    const raw = 'I had a thought { not quite right } let me try: {"answer":42}';
    expect(extractJsonObject(raw)).toEqual({ answer: 42 });
  });

  it('parses a structure resembling the Summary_Engine output schema', () => {
    const raw = [
      '```json',
      '{',
      '  "summary": "Discussed roadmap and Q3 priorities.",',
      '  "actionItems": [{ "text": "Send recap email" }],',
      '  "followUpEmail": "Hi team, here is the recap...",',
      '  "keyFacts": ["Alice owns the launch", "Budget is fixed"]',
      '}',
      '```',
      '',
      'Let me know if you need anything else.',
    ].join('\n');

    const parsed = extractJsonObject(raw);
    expect(parsed).toEqual({
      summary: 'Discussed roadmap and Q3 priorities.',
      actionItems: [{ text: 'Send recap email' }],
      followUpEmail: 'Hi team, here is the recap...',
      keyFacts: ['Alice owns the launch', 'Budget is fixed'],
    });
  });
});

// ----------------------------------------------------------------------------
// Property 28: JSON extractor is round-trip exact.
// Validates: Requirement 10.2.
//
// For any object generated by fast-check, JSON.stringify(obj) wrapped in
// arbitrary leading/trailing text and/or markdown code fences should round-trip
// to the same object via extractJsonObject.
// ----------------------------------------------------------------------------

/**
 * Generates JSON-safe object values: objects whose values are primitives,
 * arrays, or nested objects, all serializable. We use fc.object() with a
 * controlled depth so each shrink stays tractable.
 */
const jsonObjectArb = fc.object({
  maxDepth: 4,
  maxKeys: 5,
  // Restrict leaf values to JSON-representable kinds. fc.object's default
  // generators include `undefined`, which `JSON.stringify` drops; that would
  // cause a round-trip mismatch through no fault of the extractor.
  values: [
    fc.string(),
    fc.integer(),
    fc.float({ noNaN: true, noDefaultInfinity: true }),
    fc.boolean(),
    fc.constant(null),
  ],
});

/**
 * Wrap a piece of text with arbitrary leading/trailing commentary and
 * optionally a ```json or ``` code fence. The text passed in must NOT itself
 * contain a closing fence ``` so the wrapper does not become ambiguous.
 */
function wrappedTextArb(inner: string): fc.Arbitrary<string> {
  // Commentary must not contain `{` so it cannot accidentally be parsed as
  // the candidate object before the real one. Trailing commentary may contain
  // `{` because we only return the FIRST balanced parse.
  // We also exclude the backtick character so we never accidentally produce a
  // closing fence inside commentary that would prematurely terminate a fenced
  // wrapper in the rendered string.
  const safeCommentary = fc
    .string({ maxLength: 40 })
    .map((s) => s.replace(/[{`]/g, ' '));

  return fc.tuple(safeCommentary, safeCommentary, fc.constantFrom('none', 'json', 'plain')).map(
    ([before, after, fenceKind]) => {
      const fenceOpen =
        fenceKind === 'json' ? '```json\n' : fenceKind === 'plain' ? '```\n' : '';
      const fenceClose = fenceKind === 'none' ? '' : '\n```';
      return `${before}\n${fenceOpen}${inner}${fenceClose}\n${after}`;
    }
  );
}

/**
 * Combined arbitrary that produces `{ obj, wrapped }` where `wrapped` contains
 * `JSON.stringify(obj)` plus arbitrary commentary and optional code fences.
 */
const wrappedObjectArb = jsonObjectArb.chain((obj) =>
  wrappedTextArb(JSON.stringify(obj)).map((wrapped) => ({ obj, wrapped }))
);

describe('extractJsonObject (Property 28)', () => {
  // Validates: Requirement 10.2.
  it('round-trips arbitrary JSON objects through wrapping commentary and fences', () => {
    fc.assert(
      fc.property(wrappedObjectArb, ({ obj, wrapped }) => {
        const extracted = extractJsonObject(wrapped);
        expect(extracted).toEqual(obj);
      }),
      { numRuns: 200 }
    );
  });
});
